package net.acomputerdog.BlazeLoader.mod.resource;

import net.acomputerdog.BlazeLoader.mod.Mod;
import net.minecraft.client.resources.FolderResourcePack;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;

public class BLModResourcePackDir extends FolderResourcePack
{
    public Mod mod;

    public BLModResourcePackDir(File modFile, Mod mod)
    {
        super(modFile);
        this.mod = mod;
    }

    @Override
    public String getPackName()
    {
        return "BLModResourcePackDir:" + mod.getModId();
    }

    @Override
    protected InputStream getInputStreamByName(String name) throws IOException
    {
        try
        {
            return super.getInputStreamByName(name);
        }
        catch (IOException e)
        {
            if (name.equals("pack.mcmeta"))
            {
                return new ByteArrayInputStream(("{\n" +
                        " \"pack\": {\n" +
                        "   \"description\": \"default pack.mcmeta generated by BL for " + mod.getModId() + "\",\n" +
                        "   \"pack_format\": 1\n" +
                        "}\n" +
                        "}").getBytes());
            }
            else
                throw e;
        }
    }
}
